using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;
using ZCompileDesc.Utils;

namespace ZCompileDesc.Descriptions
{
    public class ZCLocalVar : IIdent, ICompling
    {
        //public bool IsAssigned { get; set; }
        public int LoacalVarIndex { get; set; }
        public LocalBuilder VarBuilder { get; set; }
        public string ZName { get; set; }
        public ZType ZType { get; set; }
        public ZType GetZType() { return this.ZType; } 
        //public bool IsStruct { get { return ZTypeUtil.IsStruct(this.GetZType()); } }
        public bool GetCanWrite() { return true; }
        public bool GetCanRead() { return true; }
       
        /// <summary>
        /// 是否是编译器自动生成
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        public bool IsNestedClassInstance { get; set; }

        public bool IsReplaceToNestedFiled { get; set; }

        public ZCLocalVar(string name, ZType type)
        {
            this.ZName = name;
            ZType = type;
        }

        public ZCLocalVar(string name, ZType type, bool isAutoGenerated)
        {
            this.ZName = name;
            ZType = type;
            IsAutoGenerated = isAutoGenerated;
        }

        //public bool GetCanRead
        //{
        //    get
        //    {
        //        return true;
        //    }
        //}

        //public bool GetCanWrite
        //{
        //    get
        //    {
        //        return true;
        //    }
        //}

        public override string ToString()
        {
            return "变量(" + GetZType().ZTypeName + ":" + ZName + ")";
            //throw new CCException();
        }

        public bool IsInBlock { get; set; }

    }
}
